name: publish

on:
  push: { tags: ["v*"] }

permissions:
  id-token: write # Required for OIDC.
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { registry-url: "https://registry.npmjs.org" }

      - run: npm run review
      - run: npm run build
      - run: npm run pub
