name: review

on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run review
