name: review

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run review
      - run: npm run build

      - run: npx releaselog -f notes ${{ github.ref_name }} > .changelog
      - env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        run: >-
          gh release create ${{ github.ref_name }}
          --title ${{ github.ref_name }}
          --notes-file .changelog
